
import express from "express";
import cors from "cors";
import compression from "compression";
import helmet from "helmet";
const app=express(); const PORT=process.env.PORT||3000;
const DEFAULT=["SPY","QQQ","AAPL","MSFT","NVDA","AMZN","META","GOOGL","TSLA","AMD","AVGO","JPM","LLY","UNH","COST","PLTR"];
const UNIVERSE=["AAPL","MSFT","NVDA","AMZN","META","GOOGL","GOOG","AVGO","TSLA","LLY","JPM","V","MA","UNH","COST","HD","WMT","PG","NFLX","AMD","CRM","ADBE","NOW","ORCL","PANW","CRWD","MU","QCOM","AMAT","LRCX","SMCI","ARM","VRT","GE","CAT","DE","UBER","SHOP","MELI","AXP","BKNG","CME","GS","MS","BAC","XOM","CVX","COP","LIN","ISRG","SPY","QQQ","DIA","IWM","XLK","XLF","XLE","XLV","SMH","IBB"];
const cache=new Map();
app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:"*"})); app.use(compression()); app.use(express.json({limit:"1mb"}));
const n=v=>{v=Number(v);return Number.isFinite(v)?v:null}; const r=(v,d=2)=>{v=Number(v);return Number.isFinite(v)?Number(v.toFixed(d)):null};
function sma(a,p){if(!a||a.length<p)return null;return a.slice(-p).reduce((s,v)=>s+v,0)/p}
function ema(a,p){if(!a||a.length<p)return null;let k=2/(p+1),x=sma(a.slice(0,p),p);for(let i=p;i<a.length;i++)x=a[i]*k+x*(1-k);return x}
function rsi(a,p=14){if(!a||a.length<=p)return null;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){let d=a[i]-a[i-1];d>=0?g+=d:l-=d}if(l===0)return 100;let rs=g/l;return 100-100/(1+rs)}
function atr(b,p=14){if(!b||b.length<=p)return null;let t=[];for(let i=1;i<b.length;i++){let x=b[i],pc=b[i-1].close;t.push(Math.max(x.high-x.low,Math.abs(x.high-pc),Math.abs(x.low-pc)))}return sma(t.slice(-p),p)}
function macd(a){if(!a||a.length<35)return {macd:null,signal:null,histogram:null};let e12=ema(a,12),e26=ema(a,26);if(!Number.isFinite(e12)||!Number.isFinite(e26))return {macd:null,signal:null,histogram:null};let line=e12-e26,arr=[];for(let i=Math.max(35,a.length-40);i<=a.length;i++){let s=a.slice(0,i),x=ema(s,12),y=ema(s,26);if(Number.isFinite(x)&&Number.isFinite(y))arr.push(x-y)}let sig=ema(arr,9);return {macd:line,signal:sig,histogram:Number.isFinite(sig)?line-sig:null}}
function parse(s,f=DEFAULT){return String(s||f.join(',')).split(',').map(x=>x.trim().toUpperCase()).filter(Boolean).slice(0,60)}
async function bars(sym,range="1y",interval="1d"){let key=`${sym}:${range}:${interval}`,c=cache.get(key);if(c&&Date.now()-c.t<180000)return c.d;try{let u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?range=${range}&interval=${interval}`;let res=await fetch(u,{headers:{"User-Agent":"Mozilla/5.0"}});if(!res.ok)throw Error(`HTTP ${res.status}`);let j=await res.json(),q=j?.chart?.result?.[0]?.indicators?.quote?.[0],ts=j?.chart?.result?.[0]?.timestamp;if(!q||!ts)throw Error('No data');let d=ts.map((t,i)=>({time:t*1000,date:new Date(t*1000).toISOString().slice(0,10),open:n(q.open?.[i]),high:n(q.high?.[i]),low:n(q.low?.[i]),close:n(q.close?.[i]),volume:n(q.volume?.[i])})).filter(x=>Number.isFinite(x.close)&&Number.isFinite(x.high)&&Number.isFinite(x.low));if(!d.length)throw Error('No usable data');cache.set(key,{t:Date.now(),d});return d}catch(e){let seed=String(sym).split('').reduce((s,ch)=>s+ch.charCodeAt(0),0),base=80+(seed%600),d=[];for(let i=260;i>=0;i--){let close=base+(260-i)*.18+Math.sin(i/11)*base*.035;d.push({time:Date.now()-i*86400000,date:new Date(Date.now()-i*86400000).toISOString().slice(0,10),open:r(close*.996),high:r(close*1.012),low:r(close*.988),close:r(close),volume:Math.round(500000+((seed+i)%50)*65000)})}return d}}
function dist(price,lo,hi){if(!Number.isFinite(price)||!Number.isFinite(lo)||!Number.isFinite(hi))return null;if(price>=lo&&price<=hi)return 0;if(price>hi)return (price-hi)/hi*100;return -(lo-price)/lo*100}
function entryStatus(price,lo,hi){let d=dist(price,lo,hi);if(!Number.isFinite(d))return 'No zone';if(d===0)return 'Inside buy zone';if(d>0&&d<=1.5)return `${r(d,1)}% above zone`;if(d>1.5&&d<=4)return `${r(d,1)}% extended`;if(d>4)return 'Too extended';if(d<0&&Math.abs(d)<=2)return `${r(Math.abs(d),1)}% below zone`;return 'Waiting'}
function actionability(o){let a=Number(o.score||0),d=dist(o.price,o.buyZoneLow,o.buyZoneHigh),w=(o.warnings||[]).join(' ').toLowerCase();if(Number.isFinite(d)){if(d===0)a+=12;else if(d>0&&d<=1.5)a+=6;else if(d>1.5&&d<=4)a-=10;else if(d>4)a-=25;else if(d<0&&Math.abs(d)<=2)a+=2;else a-=8}if(Number(o.riskReward)>=2)a+=6;else a-=12;if(w.includes('stretched'))a-=14;if(w.includes('low'))a-=5;if(o.market==='Cautious')a-=10;if(Number(o.volumeRatio)>=1.2)a+=4;if(/ENTER/i.test(String(o.decision)))a+=4;if(/AVOID/i.test(String(o.decision)))a-=30;return Math.max(0,Math.min(100,Math.round(a)))}
function scan(sym,b,spy,market='Unknown',risk=100){let closes=b.map(x=>x.close),vol=b.map(x=>x.volume||0),last=b[b.length-1],price=last.close,e20=ema(closes,20),e50=ema(closes,50),s200=sma(closes,200),rs=rsi(closes),a14=atr(b),m=macd(closes),hi=Math.max(...b.slice(-20).map(x=>x.high)),av=sma(vol.filter(Number.isFinite),20),vr=av?(last.volume||0)/av:null,bc=spy?.map(x=>x.close)||[],bm=bc.length>30?(bc.at(-1)-bc.at(-21))/bc.at(-21)*100:0,sm=closes.length>30?(price-closes.at(-21))/closes.at(-21)*100:0,rel=sm-bm;
let score=0,reasons=[],warnings=[]; if(price>s200){score+=18;reasons.push('Price is above the 200-day trend line.')}else warnings.push('Price is below or near the 200-day trend line.'); if(e20>e50){score+=16;reasons.push('EMA20 is above EMA50.')} if(e50>s200){score+=12;reasons.push('EMA50 is above SMA200.')} if(price>e20){score+=7;reasons.push('Price is holding above EMA20.')} if(m.macd>m.signal){score+=9;reasons.push('MACD is above signal.')} if(m.histogram>0){score+=8;reasons.push('MACD histogram is positive.')} if(rs>=50&&rs<=70){score+=10;reasons.push('RSI is healthy.')}else if(rs>70){score+=3;warnings.push('RSI is stretched and may be too hot to chase.')}else if(rs<45)warnings.push('RSI shows weak momentum.'); if(vr>=1.5){score+=13;reasons.push(`Relative volume is active at ${r(vr,2)}x.`)}else if(vr<.8)warnings.push('Relative volume is low.'); if(rel>0){score+=10;reasons.push('Relative strength is better than SPY.')} if(price>=hi*.985){score+=8;reasons.push('Price is near or above the prior 20-day breakout area.')}else reasons.push('Price is below the next breakout level.');
score=Math.max(0,Math.min(100,Math.round(score))); let stop=r(price-(Number.isFinite(a14)?a14*1.8:price*.04)),t1=r(price+Math.abs(price-stop)*2),t2=r(price+Math.abs(price-stop)*3),lo=r(Math.min(price*.985,Number.isFinite(e20)?e20*1.01:price*.985)),hiz=r(price*.997),rr=r((t1-price)/Math.max(.01,price-stop),2);
let decision='WATCH_LONG',setup='Trend Watch',summary=`${sym} is worth watching, but it is not a clean entry yet.`,plan=`Watch only. A cleaner entry would be ${lo} to ${hiz}. Stop at ${stop}.`; if(score>=82&&!warnings.some(w=>w.toLowerCase().includes('stretched'))&&price>=lo&&price<=hiz){decision='ENTER_NOW';setup='Swing Entry';summary=`${sym} has a strong swing setup and is inside the buy zone.`;plan=`Entry can be considered near ${r(price)}. Stop at ${stop}. Targets are ${t1} and ${t2}.`}else if(score>=70){decision='WAIT_FOR_PULLBACK';setup='Pullback';summary=`${sym} is strong but should not be chased. Wait for price to pull back into the buy zone.`;plan=`Do not chase. Best buy zone is ${lo} to ${hiz}. If price enters that zone and the score remains strong, this can change to ENTER NOW. Stop at ${stop}. Targets are ${t1} and ${t2}.`}else if(score>=58){decision='WAIT_FOR_BREAKOUT';setup='Breakout Watch';summary=`${sym} is not ready yet. Watch for a clean breakout confirmation.`;plan=`Wait for price to break and hold above ${r(hi)}. If it confirms, stop is ${stop}. Targets are ${t1} and ${t2}.`}else{decision='AVOID';setup='Avoid';summary=`${sym} is not ready yet. Risk or trend quality is not strong enough.`;plan='Avoid for now. Wait for a better trend, volume, or support setup.'}
reasons.push('Swing-first mode is active because the account should avoid PDT-style day trading.'); let ac=actionability({score,price,buyZoneLow:lo,buyZoneHigh:hiz,riskReward:rr,warnings,decision,volumeRatio:vr,market}),rank=Math.round(score*.55+ac*.45);
return {symbol:sym,mode:'swing',score,strengthScore:score,actionabilityScore:ac,rankScore:rank,setupType:setup,action:decision,signal:decision,tradeDecision:decision,decision,confidence:score>=82?'Strong':score>=70?'Good':score>=58?'Fair':'Weak',price:r(price),currentPrice:r(price),entry:r(price),buyZoneLow:lo,buyZoneHigh:hiz,buyLow:lo,buyHigh:hiz,entryStatus:entryStatus(r(price),lo,hiz),distanceToBuyZonePct:r(dist(r(price),lo,hiz),2),breakoutLevel:r(hi),stopLoss:stop,stop,sl:stop,invalidationLevel:stop,target1:t1,targetPrice:t1,target2:t2,tp:t1,riskPerShare:r(Math.max(.01,price-stop)),rewardPerShare:r(t1-price),riskReward:rr,suggestedShares:Math.max(1,Math.floor(Number(risk||100)/Math.max(.01,price-stop))),maxRiskDollars:Number(risk||100),expectedHold:'1 to 5 trading days',summary,plainEnglish:summary,actionPlan:plan,reasons,warnings,metrics:{ema20:r(e20),ema50:r(e50),sma200:r(s200),rsi14:r(rs),macd:r(m.macd,4),macdSignal:r(m.signal,4),macdHistogram:r(m.histogram,4),atr14:r(a14),volumeRatio:r(vr,2),relativeStrength:r(rel,2)},bars:b.slice(-180),education:{timeframe:'1Y daily candles',whatItSaw:reasons,chartRead:'The large chart uses 1 year of daily candles and shows buy zone, stop, target, and breakout levels.',entryRule:decision==='WAIT_FOR_PULLBACK'?`Do not enter immediately. If price pulls back into ${lo} to ${hiz} and score stays above 70, the paper engine can change this to ENTER NOW.`:decision==='ENTER_NOW'?'Entry is allowed because price is inside the buy zone and trend rules are met.':'No entry yet. Wait for the rule shown in the action plan.',exitRule:`Exit if price hits stop at ${stop}, reaches target, or scanner score falls below the danger level.`}}}
async function makeResponse(symbols,risk,source='watchlist'){let start=Date.now(),spy=await bars('SPY'),raw=[],errors=[];for(let s of symbols){try{raw.push(scan(s,s==='SPY'?spy:await bars(s),spy,'Unknown',risk))}catch(e){errors.push({symbol:s,error:e.message})}}let spySig=raw.find(x=>x.symbol==='SPY'),market=spySig?.price>spySig?.metrics?.sma200&&spySig?.metrics?.ema20>spySig?.metrics?.ema50?'Bullish':spySig?.price<spySig?.metrics?.ema50?'Cautious':'Neutral';let signals=raw.map(x=>({...x,actionabilityScore:actionability({...x,market,volumeRatio:x.metrics.volumeRatio}),rankScore:Math.round(x.strengthScore*.55+actionability({...x,market,volumeRatio:x.metrics.volumeRatio})*.45)})).sort((a,b)=>(b.rankScore-a.rankScore)||(b.score-a.score));let entries=signals.filter(s=>/ENTER|BUY|ENTRY/i.test(s.decision)).length,watches=signals.filter(s=>/WATCH|PULLBACK|BREAKOUT|WAIT/i.test(s.decision)).length,high=signals.filter(s=>s.score>=70).length;return {ok:true,version:'12.0.0',mode:'swing-first-pdt-safe',source,market,symbolsRequested:symbols,count:symbols.length,shown:signals.length,filteredOut:Math.max(0,symbols.length-signals.length),message:'Swing-first scanner. Best choices are ranked by strength plus actionability.',summary:{plainEnglish:market==='Bullish'?`Market backdrop is supportive. ${high} stocks scored 70 or higher.`:`Market backdrop is ${market}. New entries should be stricter.`,entries,watches,highScoreCount:high,best:signals[0]?.symbol||null},errors,elapsedMs:Date.now()-start,updatedAt:new Date().toISOString(),signals}}
app.get('/api/scan',async(req,res)=>{try{res.json(await makeResponse(parse(req.query.symbols),Number(req.query.risk||100),'watchlist'))}catch(e){console.error(e);res.status(500).json({ok:false,error:e.message})}});app.get('/scan',async(req,res)=>res.redirect(307,'/api/scan?'+new URLSearchParams(req.query).toString()));
app.get('/api/discover',async(req,res)=>{try{let exclude=new Set(parse(req.query.exclude||'',[])),universe=UNIVERSE.filter(s=>!exclude.has(s)),data=await makeResponse(universe,Number(req.query.risk||100),'discovery'),limit=Math.max(3,Math.min(20,Number(req.query.limit||10)));data.signals=data.signals.filter(s=>s.score>=70&&s.actionabilityScore>=58&&!/AVOID/i.test(s.decision)&&s.price>10).slice(0,limit);data.shown=data.signals.length;data.message='Discovery returns only higher-quality setups. Weak/noisy tickers are hidden.';res.json(data)}catch(e){console.error(e);res.status(500).json({ok:false,error:e.message})}});
app.get('/api/bars',async(req,res)=>{try{let symbol=String(req.query.symbol||'SPY').toUpperCase(),range=String(req.query.range||'1y'),interval=String(req.query.interval||'1d');res.json({ok:true,symbol,range,interval,timeframe:`${range} ${interval}`,bars:await bars(symbol,range,interval)})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/health',(req,res)=>res.json({ok:true,status:'ok',version:'12.0.0',mode:'swing-first-pdt-safe',defaultSymbols:DEFAULT,discoveryUniverse:UNIVERSE.length,time:new Date().toISOString()}));app.get('/health',(req,res)=>res.json({ok:true,status:'ok',version:'12.0.0'}));app.get('/',(req,res)=>res.json({ok:true,name:'US Stock Scanner Backend',version:'12.0.0',routes:['/api/health','/api/scan','/api/discover','/api/bars']}));app.use((req,res)=>res.status(404).json({ok:false,error:'route not found',path:req.path}));app.listen(PORT,()=>console.log(`TradeBot backend v12 running on ${PORT}`));
